# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Convert document.cookie string to Netscape-format cookie file for yt-dlp."""
import sys, os
from datetime import datetime, timezone, timedelta

def main():
    if len(sys.argv) < 2:
        print("Usage: python convert_cookie.py <cookie_string_or_file> [output_path]")
        print("  cookie_string_or_file: raw 'document.cookie' string, or path to a file containing it")
        print("  output_path: where to write Netscape cookie file (default: ./cookies_netscape.txt)")
        sys.exit(1)

    input_arg = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else "cookies_netscape.txt"

    # Read cookie content — either from a file or as a raw string
    if os.path.isfile(input_arg):
        with open(input_arg, "r", encoding="utf-8") as f:
            raw = f.read().strip()
    else:
        raw = input_arg.strip()

    # Expiry far in the future
    expires = int((datetime.now(timezone.utc) + timedelta(days=365 * 2)).timestamp())

    lines = ["# Netscape HTTP Cookie File", "# Auto-generated by douyin-batch-transcriber", ""]

    count = 0
    for pair in raw.split(";"):
        pair = pair.strip()
        if "=" not in pair:
            continue
        name, _, value = pair.partition("=")
        name = name.strip()
        value = value.strip()
        if not name or not value:
            continue
        # .douyin.com covers douyin.com, www.douyin.com, iesdouyin.com, etc.
        lines.append(f".douyin.com\tTRUE\t/\tFALSE\t{expires}\t{name}\t{value}")
        count += 1

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"✅ Converted {count} cookies → {output_path}")
    print(f"   Ready for: --cookie-file {output_path}")

if __name__ == "__main__":
    main()
